### ISSUE TITLE
Clear name

### ISSUE THREAD

**Issue by ai** [whitneyit/postcss-strip#3]
Maybe `postcss-strip-units` will be more clear name? See [PostCSS Plugin Guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md) 1.1.

**Comment by whitneyit** [comment]
The main purpose of this is to work with vertical rhythm and converting between `px` and `em`. I'll update the readme with your recommendations.

**Comment by whitneyit** [comment]
Name has been updated and can be found at https://github.com/whitneyit/postcss-strip-units

**Comment by ai** [comment]
GitHub allows to just rename project. It is a better way, because it creates a redirects.

**Comment by whitneyit** [comment]
Yea but it was already published to npm. So I deprecated the previous module.
